"""fix daily_logs columns

Revision ID: db1e2d6fe105
Revises: 15a385300a6f
Create Date: 2026-01-10 21:08:38.165855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1e2d6fe105'
down_revision: Union[str, None] = '15a385300a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_logs', sa.Column('coffee_last_6h', sa.Boolean(), nullable=True))
    op.add_column('daily_logs', sa.Column('alcohol_last_4h', sa.Boolean(), nullable=True))
    op.drop_column('daily_logs', 'alcohol_after_18')
    op.drop_column('daily_logs', 'coffee_after_16')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_logs', sa.Column('coffee_after_16', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('daily_logs', sa.Column('alcohol_after_18', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('daily_logs', 'alcohol_last_4h')
    op.drop_column('daily_logs', 'coffee_last_6h')
    # ### end Alembic commands ###
