"""add daily_logs and update user

Revision ID: db5c953bb7f6
Revises: bcb58009048e
Create Date: 2025-12-01 17:50:05.711034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db5c953bb7f6'
down_revision: Union[str, None] = 'bcb58009048e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_start', sa.DateTime(), nullable=True),
    sa.Column('sleep_latency_extra', sa.Integer(), nullable=True),
    sa.Column('sleep_end', sa.DateTime(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('night_awakenings', sa.Integer(), nullable=True),
    sa.Column('morning_energy', sa.Integer(), nullable=True),
    sa.Column('day_rating', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('coffee_after_16', sa.Boolean(), nullable=True),
    sa.Column('alcohol_after_18', sa.Boolean(), nullable=True),
    sa.Column('screens_last_hour', sa.Enum('low', 'medium', 'high', name='screenslasthour'), nullable=True),
    sa.Column('nap_type', sa.Enum('none', 'short', 'medium', 'long', name='naptype'), nullable=True),
    sa.Column('sleep_duration', sa.Float(), nullable=True),
    sa.Column('day_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_logs_user_id'), 'daily_logs', ['user_id'], unique=False)
    op.drop_table('entries')
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('typical_sleep_latency', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'typical_sleep_latency')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'name')
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('mood', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sleep_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exercise_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='entries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entries_pkey')
    )
    op.drop_index(op.f('ix_daily_logs_user_id'), table_name='daily_logs')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###
